"use client";

import { YueYuanMark } from "@/components/cf/ui/YueYuanMark";
import { useLocale } from "@/components/i18n/use-locale";
import { commonTranslations, translate } from "@/config/i18n";
import { type ReactNode, useEffect } from "react";
import { BaseLayout } from "./BaseLayout";

interface CFLayoutProps {
  children: ReactNode;
}

export const CFLayout = ({ children }: CFLayoutProps) => {
  const locale = useLocale();

  useEffect(() => {
    const applyRayId = () => {
      const fallback = locale === "zh" ? "待生成" : "Pending";
      const detailText =
        document.querySelector(".yy-detail__box, .yy-widget__box")
          ?.textContent ?? "";
      const detailRayId =
        detailText.match(/Ray\s*ID:\s*([a-f0-9]{16,32})/i)?.[1] ?? "";

      for (const node of document.querySelectorAll<HTMLElement>(
        "[data-ray-id]",
      )) {
        const value = node.textContent?.trim() ?? "";
        if (
          !value ||
          value.includes("::RAY_ID::") ||
          value === "7F4C-9A21-RAY" ||
          value === "由 Cloudflare 生成" ||
          value === "Generated by Cloudflare" ||
          value === "待生成" ||
          value === "Pending"
        ) {
          node.textContent = detailRayId || fallback;
        }
      }
    };

    applyRayId();

    if (typeof MutationObserver === "undefined") {
      return;
    }

    const observer = new MutationObserver(applyRayId);

    for (const source of document.querySelectorAll(
      ".yy-detail__box, .yy-widget__box",
    )) {
      observer.observe(source, {
        characterData: true,
        childList: true,
        subtree: true,
      });
    }

    return () => observer.disconnect();
  }, [locale]);

  return (
    <BaseLayout>
      <div className="yy-shell">
        <div className="yy-scenery" aria-hidden="true">
          <div className="yy-orbit" />
          <div className="yy-cloud yy-cloud--left" />
          <div className="yy-cloud yy-cloud--right" />
          <div className="yy-wall yy-wall--left" />
          <div className="yy-mountain yy-mountain--back" />
          <div className="yy-mountain yy-mountain--middle" />
          <div className="yy-mountain yy-mountain--front" />
        </div>

        <header className="yy-brand" aria-label="YueYuan Edge Security">
          <YueYuanMark compact />
          <span className="yy-brand__text">
            {translate(commonTranslations.yueYuanBrand, locale)}
          </span>
        </header>

        <aside className="yy-vertical" aria-hidden="true">
          <span>
            {translate(commonTranslations.yueYuanVerticalTop, locale)}
          </span>
          <span>
            {translate(commonTranslations.yueYuanVerticalBottom, locale)}
          </span>
          <i className="yy-seal">
            <span>{translate(commonTranslations.yueYuanSealTop, locale)}</span>
            <span>
              {translate(commonTranslations.yueYuanSealBottom, locale)}
            </span>
          </i>
        </aside>

        <main className="yy-main">
          <div className="yy-main__inner">{children}</div>
        </main>

        <footer className="yy-protected">
          <span className="yy-protected__shield" aria-hidden="true" />
          <span className="yy-protected__text">
            {translate(commonTranslations.yueYuanProtectedBy, locale)}
          </span>
        </footer>
      </div>
    </BaseLayout>
  );
};

export default CFLayout;
